export type RankingPeriod = "week" | "month" | "all";

export interface RankingUser {
  id: string;
  rank: number;
  name: string;
  avatarUrl?: string;
  initials: string;
  badgeTitle: string;
  preference: string;
  location?: string;
  orderCount: number;
  orderCountLabel: string;
  reward: string;
  privilegeHighlight?: string;
}

export interface PeriodRankingData {
  period: RankingPeriod;
  badgeLabel: string;
  top3: [RankingUser, RankingUser, RankingUser]; // [Rank 2, Rank 1, Rank 3] for podium display
  chasers: RankingUser[]; // Rank 4 to 6
  fullLeaderboard: RankingUser[]; // Rank 1 to 10
  personalStatus: {
    rank: number;
    neededOrders: number;
    targetRank: number;
    potentialReward: string;
  };
}

export const rankingDataByPeriod: Record<RankingPeriod, PeriodRankingData> = {
  week: {
    period: "week",
    badgeLabel: "BẢNG VINH DANH TUẦN NÀY",
    top3: [
      // Index 0: Rank 2 (Bạc)
      {
        id: "user-2",
        rank: 2,
        name: "Trần Minh Quang",
        initials: "MQ",
        badgeTitle: "Gourmet Master",
        preference: "Mê Phở & Cà phê muối",
        orderCount: 42,
        orderCountLabel: "42 đơn",
        reward: "+300k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      },
      // Index 1: Rank 1 (Quán Quân)
      {
        id: "user-1",
        rank: 1,
        name: "Lê Hoàng Yến",
        initials: "HY",
        badgeTitle: "👑 Thực Thần VIP 3",
        preference: "Tín đồ Bún Bò & Cơm Tấm",
        orderCount: 48,
        orderCountLabel: "48 đơn hàng",
        reward: "Freeship cả tháng + 500k",
        privilegeHighlight: "Freeship cả tháng + 500k",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      },
      // Index 2: Rank 3 (Đồng)
      {
        id: "user-3",
        rank: 3,
        name: "Nguyễn Hà My",
        initials: "HM",
        badgeTitle: "Foodie Pro",
        preference: "Mê Trà Đào & Bánh Mì",
        orderCount: 37,
        orderCountLabel: "37 đơn",
        reward: "+200k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      },
    ],
    chasers: [
      {
        id: "user-4",
        rank: 4,
        name: "Hoàng Nam",
        initials: "HN",
        badgeTitle: "Master Eater",
        preference: "Mê Cơm Tấm",
        location: "Ninh Kiều",
        orderCount: 31,
        orderCountLabel: "31 đơn",
        reward: "+100k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-5",
        rank: 5,
        name: "Đặng Thu Hà",
        initials: "TH",
        badgeTitle: "Street Food Lover",
        preference: "Tín đồ Ăn Vặt",
        location: "Bình Thủy",
        orderCount: 29,
        orderCountLabel: "29 đơn",
        reward: "+60k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-6",
        rank: 6,
        name: "Vũ Bảo Long",
        initials: "BL",
        badgeTitle: "Phở Connoisseur",
        preference: "Nghiện Phở Bò",
        location: "Cái Răng",
        orderCount: 25,
        orderCountLabel: "25 đơn",
        reward: "+50k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
      },
    ],
    fullLeaderboard: [
      {
        id: "user-1",
        rank: 1,
        name: "Lê Hoàng Yến",
        initials: "HY",
        badgeTitle: "👑 Thực Thần VIP 3",
        preference: "Tín đồ Bún Bò & Cơm Tấm",
        location: "Ninh Kiều",
        orderCount: 48,
        orderCountLabel: "48 đơn hàng",
        reward: "Freeship cả tháng + 500k",
      },
      {
        id: "user-2",
        rank: 2,
        name: "Trần Minh Quang",
        initials: "MQ",
        badgeTitle: "Gourmet Master",
        preference: "Mê Phở & Cà phê muối",
        location: "Ninh Kiều",
        orderCount: 42,
        orderCountLabel: "42 đơn",
        reward: "+300k voucher",
      },
      {
        id: "user-3",
        rank: 3,
        name: "Nguyễn Hà My",
        initials: "HM",
        badgeTitle: "Foodie Pro",
        preference: "Mê Trà Đào & Bánh Mì",
        location: "Bình Thủy",
        orderCount: 37,
        orderCountLabel: "37 đơn",
        reward: "+200k voucher",
      },
      {
        id: "user-4",
        rank: 4,
        name: "Hoàng Nam",
        initials: "HN",
        badgeTitle: "Master Eater",
        preference: "Mê Cơm Tấm",
        location: "Ninh Kiều",
        orderCount: 31,
        orderCountLabel: "31 đơn",
        reward: "+100k voucher",
      },
      {
        id: "user-5",
        rank: 5,
        name: "Đặng Thu Hà",
        initials: "TH",
        badgeTitle: "Street Food Lover",
        preference: "Tín đồ Ăn Vặt",
        location: "Bình Thủy",
        orderCount: 29,
        orderCountLabel: "29 đơn",
        reward: "+60k voucher",
      },
      {
        id: "user-6",
        rank: 6,
        name: "Vũ Bảo Long",
        initials: "BL",
        badgeTitle: "Phở Connoisseur",
        preference: "Nghiện Phở Bò",
        location: "Cái Răng",
        orderCount: 25,
        orderCountLabel: "25 đơn",
        reward: "+50k voucher",
      },
      {
        id: "user-7",
        rank: 7,
        name: "Phạm Thảo Vy",
        initials: "TV",
        badgeTitle: "Dessert Queen",
        preference: "Mê Trà sữa & Chè",
        location: "Ninh Kiều",
        orderCount: 23,
        orderCountLabel: "23 đơn",
        reward: "+40k voucher",
      },
      {
        id: "user-8",
        rank: 8,
        name: "Ngô Quốc Huy",
        initials: "QH",
        badgeTitle: "Healthy Hunter",
        preference: "Đồ ăn Eat-Clean",
        location: "Ô Môn",
        orderCount: 21,
        orderCountLabel: "21 đơn",
        reward: "+30k voucher",
      },
      {
        id: "user-9",
        rank: 9,
        name: "Trịnh Thùy Trang",
        initials: "TT",
        badgeTitle: "Snack Specialist",
        preference: "Bánh tráng trộn",
        location: "Ninh Kiều",
        orderCount: 19,
        orderCountLabel: "19 đơn",
        reward: "+20k voucher",
      },
      {
        id: "user-10",
        rank: 10,
        name: "Đỗ Gia Huy",
        initials: "GH",
        badgeTitle: "Night Owl Foodie",
        preference: "Cơm chiên & Mì xào",
        location: "Cái Răng",
        orderCount: 18,
        orderCountLabel: "18 đơn",
        reward: "+20k voucher",
      },
    ],
    personalStatus: {
      rank: 14,
      neededOrders: 3,
      targetRank: 10,
      potentialReward: "100.000₫",
    },
  },

  month: {
    period: "month",
    badgeLabel: "BẢNG VINH DANH THÁNG NÀY",
    top3: [
      {
        id: "user-m2",
        rank: 2,
        name: "Lê Hoàng Yến",
        initials: "HY",
        badgeTitle: "👑 Thực Thần VIP 3",
        preference: "Tín đồ Bún Bò & Cơm Tấm",
        orderCount: 165,
        orderCountLabel: "165 đơn",
        reward: "+1.000k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-m1",
        rank: 1,
        name: "Trần Minh Quang",
        initials: "MQ",
        badgeTitle: "🏆 Đại Tiệc Vương",
        preference: "Mê Phở & Cà phê muối",
        orderCount: 182,
        orderCountLabel: "182 đơn hàng",
        reward: "Freeship trọn đời + 2.000k",
        privilegeHighlight: "Freeship 3 tháng + 2.000k",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-m3",
        rank: 3,
        name: "Hoàng Nam",
        initials: "HN",
        badgeTitle: "Master Eater",
        preference: "Mê Cơm Tấm",
        orderCount: 142,
        orderCountLabel: "142 đơn",
        reward: "+800k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      },
    ],
    chasers: [
      {
        id: "user-m4",
        rank: 4,
        name: "Nguyễn Hà My",
        initials: "HM",
        badgeTitle: "Foodie Pro",
        preference: "Mê Trà Đào & Bánh Mì",
        location: "Bình Thủy",
        orderCount: 128,
        orderCountLabel: "128 đơn",
        reward: "+500k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-m5",
        rank: 5,
        name: "Đặng Thu Hà",
        initials: "TH",
        badgeTitle: "Street Food Lover",
        preference: "Tín đồ Ăn Vặt",
        location: "Bình Thủy",
        orderCount: 115,
        orderCountLabel: "115 đơn",
        reward: "+300k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-m6",
        rank: 6,
        name: "Vũ Bảo Long",
        initials: "BL",
        badgeTitle: "Phở Connoisseur",
        preference: "Nghiện Phở Bò",
        location: "Cái Răng",
        orderCount: 98,
        orderCountLabel: "98 đơn",
        reward: "+200k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
      },
    ],
    fullLeaderboard: [],
    personalStatus: {
      rank: 28,
      neededOrders: 8,
      targetRank: 20,
      potentialReward: "300.000₫",
    },
  },

  all: {
    period: "all",
    badgeLabel: "BẢNG VÀNG MỌI THỜI ĐẠI",
    top3: [
      {
        id: "user-a2",
        rank: 2,
        name: "Trần Minh Quang",
        initials: "MQ",
        badgeTitle: "Huyền Thoại Ẩm Thực",
        preference: "Mê Phở & Cà phê muối",
        orderCount: 980,
        orderCountLabel: "980 đơn",
        reward: "Thành viên Hoàng Kim",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-a1",
        rank: 1,
        name: "Lê Hoàng Yến",
        initials: "HY",
        badgeTitle: "👑 Thực Thần Bất Tử",
        preference: "Tín đồ Bún Bò & Cơm Tấm",
        orderCount: 1240,
        orderCountLabel: "1.240 đơn hàng",
        reward: "Huy Hiệu Kim Cương Vĩnh Viễn",
        privilegeHighlight: "Huy hiệu Kim Cương & Giảm 15% trọn đời",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-a3",
        rank: 3,
        name: "Hoàng Nam",
        initials: "HN",
        badgeTitle: "Đại Tiệc Tinh Anh",
        preference: "Mê Cơm Tấm",
        orderCount: 860,
        orderCountLabel: "860 đơn",
        reward: "Thành viên Bạch Kim",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      },
    ],
    chasers: [
      {
        id: "user-a4",
        rank: 4,
        name: "Nguyễn Hà My",
        initials: "HM",
        badgeTitle: "Foodie Pro",
        preference: "Mê Trà Đào & Bánh Mì",
        location: "Bình Thủy",
        orderCount: 750,
        orderCountLabel: "750 đơn",
        reward: "+1.000k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-a5",
        rank: 5,
        name: "Đặng Thu Hà",
        initials: "TH",
        badgeTitle: "Street Food Lover",
        preference: "Tín đồ Ăn Vặt",
        location: "Bình Thủy",
        orderCount: 680,
        orderCountLabel: "680 đơn",
        reward: "+800k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      },
      {
        id: "user-a6",
        rank: 6,
        name: "Vũ Bảo Long",
        initials: "BL",
        badgeTitle: "Phở Connoisseur",
        preference: "Nghiện Phở Bò",
        location: "Cái Răng",
        orderCount: 620,
        orderCountLabel: "620 đơn",
        reward: "+500k voucher",
        avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
      },
    ],
    fullLeaderboard: [],
    personalStatus: {
      rank: 85,
      neededOrders: 15,
      targetRank: 50,
      potentialReward: "500.000₫",
    },
  },
};
